repos:
  - repo: local
    hooks:
      - id: coggify
        name: cog
        additional_dependencies:
          - "cogapp>=3.4.1"
          - "requests>=2.31.0"
        entry: python -m cogapp -r
        language: python
        files: '.+\.md'
