repos:
  - repo: local
    hooks:
      - id: coggify
        name: cog
        additional_dependencies:
          - "cogapp"
        entry: python -m cogapp -r @.cog-file-list.txt
        language: python
        # Make pre-commit not pass filenames to `entry` since the filenames are managed by .cog-file-list.txt
        pass_filenames: false
